### ISSUE TITLE
Using IDs to Create Hyperlinks

### ISSUE THREAD

**Issue by cyouh95** [LetsGetItDone/teacozy#2]
Instead of using `class`es for each of the main section containers of your page (ie. `.landing-container`, `.selection-container`, `.locations-content`), you can use `id`s. This will allow you to create hyperlinks to jump to that section of the page. For example,

HTML:
```html
<span><a href="#landing-container">Mission</a></span>
```
https://github.com/LetsGetItDone/teacozy/blob/master/index.html#L16

```html
<div id="landing-container">
```
https://github.com/LetsGetItDone/teacozy/blob/master/index.html#L28

CSS:
```css
#landing-container {
  ...
}
```
https://github.com/LetsGetItDone/teacozy/blob/master/resources/style.css#L47

**Comment by LetsGetItDone** [comment]
Will work on using id's in future project. Thank you for the observation.
