### ISSUE TITLE
Logo Image

### ISSUE THREAD

**Issue by cyouh95** [LetsGetItDone/teacozy#4]
To preserve the aspect ratio of your logo image, try changing the selector here to `.logo img`:

https://github.com/LetsGetItDone/teacozy/blob/4605dedbbf2493165ec40b8f4bd0ad086c0afeb3/resources/style.css#L30-L34

**Comment by LetsGetItDone** [comment]
Fix aspect ration of logo image to 
https://github.com/LetsGetItDone/teacozy/blob/e8a38e2f0e3beccb5f25331138609668a7642fde/resources/style.css#L30-L34
